---
image: docker:19.03

services:
  - docker:19.03-dind

variables:
  IMAGE_NAME: lansible/mosquitto

include:
  - project: https://github.com/LANsible/gitlab-includes.git
    ref: master
    file: docker-login.yml
  - project: https://github.com/LANsible/gitlab-includes.git
    ref: master
    file: setup-buildx.yml
  - project: https://github.com/LANsible/gitlab-includes.git
    ref: master
    file: sast-cis-benchmark.yml

stages:
  - build
  - post-build
  - test
  - publish

build:
  script:
    - buildx build \
      --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
      .
