---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  # Change if you want to deploy to somewhere other then default
  namespace: default
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    # Config file for mosquitto
    listener 1883
    allow_anonymous false
    password_file /config/passwords
    persistence false
    log_dest stdout

  passwords: |
    # Passwords file
    mosquitto:$6$5NoZ0VhFlhc7v8P/$bVfSp/b9FhvklwyYdB3nyH8kh5YCd1V4zi+cB8u+mZyedQTMuhg05eCswdmVAGbrIgAQykAzzkJdToYoP9UEOw==